### ISSUE TITLE
Project's designers doesn't load. (2 Errors)

### ISSUE THREAD

**Issue by wompgen** [lysep-corp/CoreCheatCSGO-LSREMAKE#1]
I get this 
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0246	The type or namespace name 'Bunifu' could not be found (are you missing a using directive or an assembly reference?)	CoreCheat LSREMAKE	C:\Users\17088\Desktop\CoreCheatCSGO-LSREMAKE-2.9.9.2_CLOSE\Project_OpenSource\CoreCheat-CSGO-Reborn-master\ExpireForm\Expire.Designer.cs	253	Active

I get 2 of those errors about Bunifu and if I delete the lines it gives me even more errors.

**Comment by Lyceion** [comment]
Gonna look at it.

**Comment by Lyceion** [comment]
Fixed in [this update.](https://github.com/lysep-corp/CoreCheatCSGO-LSREMAKE/commit/8f68eabb6e50dcefb9f6e2131efa78d99a2c82a6)If it still continues, just build the all projects seperately. It will fix the issue.
